name: Libenvpp CI

on: [push, pull_request]

jobs:
  build-and-test-unix:
    strategy:
      matrix:
        build-type: [Debug, Release]
        compiler: [g++, clang++]
        os: [ubuntu-latest, ubuntu-20.04, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build-type }}

    - name: Run tests
      working-directory: ${{ github.workspace }}/build
      run: ctest -C ${{ matrix.build-type }}

  build-and-test-windows:
    strategy:
      matrix:
        build-type: [Debug, Release]
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build-type }}

    - name: Run tests
      working-directory: ${{ github.workspace }}/build
      run: ctest -C ${{ matrix.build-type }}
